
let userscore = 0 ;
let compscore = 0;

const choices = document.querySelectorAll(".choice");// we selected all choice classs div
const msg = document.querySelector("#msg");
const userScorePara = document.querySelector("#user-score");
const compScorePara = document.querySelector("#comp-score");


const drawGame = () => {
   console.log("Game was Draw");
   msg.innerText = "Game Draw play again";
   msg.style.backgroundColor = "#081b31";
};


const gencompchoice = () => {
       //stone paper sicssors
       const option = ["stone" , "paper" , "scissors"];
      const ranidx =  Math.floor(Math.random()*3);
    //   console.log(ranidx); // here we also print the index no which is generated by computer
      return option[ranidx];
};


const showWinner = (userwin , userchoice , compchoice ) => {
    if(userwin){
        userscore++
        userScorePara.innerText = userscore;
        msg.innerText = `You Win! your ${userchoice} beats ${compchoice}`;
        msg.style.backgroundColor = "green";
        
    }else{
       compscore++
       compScorePara.innerText = compscore;
        msg.innerText = `You Lost ${compchoice} beats yours ${userchoice}`;
        msg.style.backgroundColor = "red";
    }
};


const playgame = ((userchoice) => {
    console.log("User choice ",userchoice);
    //generate the compter choice ;
    const compchoice = gencompchoice();
     console.log("Comp Choice" ,compchoice);
    if(userchoice === compchoice){
               drawGame();
    }else {
        let userwin = true ;
        if(userchoice === "stone"){
            //sci or paper
           userwin =  compchoice === "paper" ? false : true ; //agar comp ne paper diya to userwin = false userhaar jayage and age scissor then userwin hojayage
           
        }else if(userchoice === "paper"){
            //rock or scissors
            userwin = compchoice === "scissors" ? false : true; 

        }else {
            //stone or paper 
           userwin =  compchoice === "stone" ? false : true; 
        }
        showWinner(userwin , userchoice , compchoice);
    }
});



choices.forEach((choice) =>{// all choice per ye travers hoga like choice one choice two choice threelike these
    choice.addEventListener("click",() => {
        let userchoice = choice.getAttribute("id"); // here we generated the userchoice
        playgame(userchoice);
    });
});
